void loadSettings() {
  prefs.begin("settings", true);       // Open in read-only mode
  NIGHT_START_HOUR = prefs.getInt("NIGHT_START_HOUR", NIGHT_START_HOUR);
  NIGHT_END_HOUR = prefs.getInt("NIGHT_END_HOUR", NIGHT_END_HOUR);
  DAY_BRIGHTNESS = prefs.getInt("DAY_BRIGHTNESS", DAY_BRIGHTNESS);
  NIGHT_BRIGHTNESS = prefs.getInt("NIGHT_BRIGHTNESS", NIGHT_BRIGHTNESS);
  DAY_SATUR = prefs.getInt("DAY_SATUR", DAY_SATUR);
  NIGHT_SATUR = prefs.getInt("NIGHT_SATUR", NIGHT_SATUR);
  DAY_COLOR = prefs.getInt("DAY_COLOR", DAY_COLOR);
  NIGHT_COLOR = prefs.getInt("NIGHT_COLOR", NIGHT_COLOR);
  LDR_READS = prefs.getInt("LDR_READS", LDR_READS);
  SHOW_DATE = prefs.getInt("SHOW_DATE", SHOW_DATE);
  SHOW_TEMPERATURE = prefs.getInt("SHOW_TEMPERATURE", SHOW_TEMPERATURE);
  SHOW_HUMIDITY = prefs.getInt("SHOW_HUMIDITY", SHOW_HUMIDITY);
  SHOW_TIME_SECONDS = prefs.getInt("SHOW_TIME_SECONDS", SHOW_TIME_SECONDS);
  SHOW_DATE_SECONDS = prefs.getInt("SHOW_DATE_SECONDS", SHOW_DATE_SECONDS);
  SHOW_TEMPERATURE_SECONDS = prefs.getInt("SHOW_TEMPERATURE_SECONDS", SHOW_TEMPERATURE_SECONDS);
  SHOW_HUMIDITY_SECONDS = prefs.getInt("SHOW_HUMIDITY_SECONDS", SHOW_HUMIDITY_SECONDS);
  prefs.end();
}

void saveSettings() {
  prefs.begin("settings", false);      // Open namespace "settings" in RW mode
  prefs.putInt("DAY_BRIGHTNESS", DAY_BRIGHTNESS);
  prefs.putInt("NIGHT_BRIGHTNESS", NIGHT_BRIGHTNESS);
  prefs.putInt("DAY_SATUR", DAY_SATUR);
  prefs.putInt("NIGHT_SATUR", NIGHT_SATUR);
  prefs.putInt("DAY_COLOR", DAY_COLOR);
  prefs.putInt("NIGHT_COLOR", NIGHT_COLOR);
  prefs.putInt("NIGHT_START_HOUR", NIGHT_START_HOUR);
  prefs.putInt("NIGHT_END_HOUR", NIGHT_END_HOUR);
  prefs.putInt("LDR_READS", LDR_READS);
  prefs.putInt("SHOW_DATE", SHOW_DATE);
  prefs.putInt("SHOW_TEMPERATURE", SHOW_TEMPERATURE);
  prefs.putInt("SHOW_HUMIDITY", SHOW_HUMIDITY);
  prefs.putInt("SHOW_TIME_SECONDS", SHOW_TIME_SECONDS);
  prefs.putInt("SHOW_DATE_SECONDS", SHOW_DATE_SECONDS);
  prefs.putInt("SHOW_TEMPERATURE_SECONDS", SHOW_TEMPERATURE_SECONDS);
  prefs.putInt("SHOW_HUMIDITY_SECONDS", SHOW_HUMIDITY_SECONDS);
  
  prefs.end();
}